// 页面内容翻译器 - 在页面加载后执行
function translatePage() {
    const lang = localStorage.getItem('ace_lang') || 'zh';
    if (lang === 'zh') return; // 中文不需要翻译
    
    const T = {
        en: {
            '王牌学院':'ACE Academy','学技能 · 拿证书 · 赚代币':'Learn · Certify · Earn',
            '区块链+AI教育平台':'Blockchain + AI Education',
            '开始学习':'Start Learning','浏览课程':'Browse Courses','立即注册':'Register Now',
            '课程方向':'Directions','平台特性':'Features','准备好开始了吗？':'Ready to start?',
            '通过推荐链接注册，连接钱包，选课学习':'Register via referral, connect wallet, start learning',
            '注册':'Register','登录':'Login',
            '第一步：输入推荐人地址':'Step 1: Referral Address',
            '第1步：输入推荐人地址':'Step 1: Referral Address',
            '第2步：安全验证':'Step 2: Security Verification',
            '第3步：连接钱包授权':'Step 3: Connect Wallet',
            '第4步：注册完成':'Step 4: Complete',
            '第1步：安全验证':'Step 1: Security',
            '第2步：连接钱包':'Step 2: Connect Wallet',
            '第3步：签名授权':'Step 3: Sign to Login',
            '推荐人钱包地址':'Referral Wallet Address','推荐人':'Referrer',
            '必须通过推荐人邀请注册':'Registration requires a referral',
            '如果有推荐链接，打开链接会自动填入':'Auto-filled if you have a referral link',
            '向右滑动完成验证':'Slide right to verify',
            '验证通过':'Verified','下一步':'Next','提交':'Submit','取消':'Cancel',
            '连接钱包并授权':'Connect Wallet','连接钱包':'Connect Wallet',
            '选择钱包':'Select Wallet','你选什么钱包':'Select your wallet',
            '小狐狸钱包':'MetaMask','扫码连接':'Scan to connect',
            '请在钱包中确认连接请求':'Please confirm in your wallet',
            '需要输入密码或指纹确认':'Enter password or fingerprint',
            '我已在钱包中确认':'I confirmed in wallet',
            '授权签名':'Sign Authorization',
            '请在钱包中确认签名授权':'Please sign in your wallet',
            '此操作不消耗Gas费':'No gas fee required',
            '我已签名':'I signed','正在连接钱包':'Connecting wallet',
            '等待钱包确认':'Waiting for wallet confirmation',
            '正在验证签名':'Verifying signature','签名验证成功':'Signature verified',
            '授权成功':'Authorized','推荐关系已绑定，注册完成':'Referral bound, registration complete',
            '身份验证通过':'Identity verified','正在签名':'Signing',
            '注册成功':'Registration Success',
            '钱包地址':'Wallet Address','用户ID':'User ID',
            '已绑定':'Bound','进入学习中心':'Enter Platform',
            '签名授权登录':'Sign to Login','登录成功':'Login Success',
            '欢迎回到王牌学院':'Welcome back to ACE Academy',
            '进入学习':'Enter','钱包已连接，请完成签名授权登录':'Wallet connected, please sign to login',
            'ACE当前价格':'ACE Price','买入 ACE':'Buy ACE','卖出 ACE':'Sell ACE',
            '支付金额':'Pay Amount','卖出数量':'Sell Amount',
            '预计获得':'Expected','手续费':'Fee','销毁':'Burn','公益':'Charity',
            '实际到账':'Received','底池':'Pool','已销毁':'Burned',
            '当前总量':'Supply','最近交易':'Recent Trades','买入':'Buy','卖出':'Sell',
            '我的推荐链接':'My Referral Link','复制':'Copy',
            '收入概览':'Income Overview','直推USDT':'Direct USDT','团队代币':'Team ACE',
            '代币释放':'Released','团队数据':'Team Data','直推人数':'Direct Count',
            '团队总人数':'Team Total','团队业绩':'Team Revenue','个人业绩':'Personal Revenue',
            '当前级别':'Current Level','下一级':'Next Level','直推明细':'Direct Details',
            '升级合伙人':'Upgrade to Partner','返回':'Back','刷新':'Refresh',
            '账户信息':'Account Info','我的资产':'My Assets','可用ACE':'Available ACE',
            '锁定ACE':'Locked ACE','代币释放进度':'Release Progress',
            '已释放':'Released','未解锁':'Locked','我的证书':'My Certificates',
            '质押生息':'Staking','质押数量':'Stake Amount','质押期':'Period',
            '年化收益':'APR','预期收益':'Expected Reward','到期时间':'Maturity',
            '新增质押':'New Stake','持有权益':'Benefits','退课':'Refund',
            '申请退课':'Apply Refund','身份':'Role','学员':'Student',
            '大使':'Ambassador','合伙人':'Partner',
            '管理后台':'Admin Panel','全网统计':'Global Stats',
            '总用户数':'Total Users','总学费收入':'Total Revenue',
            '资金钱包':'Fund Wallets','平台运营USDT':'Platform USDT',
            '护盘基金':'Protection Fund','公益基金':'Charity Fund',
            '做市管理':'Market Management','推广统计':'Promotion Stats',
            '推广者人数':'Promoters','合约地址':'Contract Addresses',
            '权限状态':'Permission Status','已丢弃':'Renounced','未丢弃':'Active',
            '管理操作':'Admin Actions','补充护盘基金':'Top Up Protection',
            '提取超出部分':'Withdraw Excess','月度回购销毁':'Monthly Buyback',
            '紧急暂停':'Emergency Pause','返回首页':'Back to Home',
            '学习进度':'Learning Progress','总学习时长':'Total Hours',
            '已学时长':'Learned Hours','已释放代币':'Released Tokens',
            '课程列表':'Course List','完成本课':'Complete','复习':'Review',
            '进行中':'In Progress','参加考试':'Take Exam',
            '综合考试':'Comprehensive Exam','考试方向':'Direction',
            '题目数量':'Questions','题型':'Type','及格分数':'Passing Score',
            '考试时长':'Duration','考试次数':'Attempts','不限':'Unlimited',
            '开始考试':'Start Exam','考试通过！':'Exam Passed!','未通过':'Failed',
            '答对':'Correct','重新考试':'Retry','铸造链上证书':'Mint Certificate',
            '课程库':'Course Library','小时内容':'hrs content',
            '课程成本':'Course Cost','入门':'Beginner','进阶':'Intermediate',
            '高级':'Advanced','观看视频':'Watch Video','实操练习':'Practice',
            '写代码':'Code','考试测评':'Exam','零基础':'Zero Base',
            '有基础':'Some Base','比较熟悉':'Proficient',
            '方向':'Direction','门课程':'courses','ACE总量':'ACE Total',
            '方案生成完毕':'Plan generated','你的专属学习方案':'Your Personalized Plan',
            '方案已确认':'Plan confirmed','付费后即可开始学习':'Pay to start learning',
            '重新规划':'Replan','确认方案':'Confirm Plan',
            '碎片时间学习':'Spare time','每天固定时间':'Fixed time daily',
            '投入较多时间':'More time','找工作':'Find a job','创业':'Start business',
            '提升技能':'Improve skills','兴趣':'Interest',
            '学技能':'Learn','拿证书':'Certify','赚代币':'Earn',

            '第1步：输入推荐人地址':'Step 1: Referral Address',
            '第1步：输入':'Step 1: Enter',
            '地址':'Address',
            '邀请注册':'to register',
            '必须通过':'Requires referral',
            '输入推荐人地址 0x...':'Enter referral address 0x...',
            '在这里输入你想学的具体内容...（可跳过）':'Type what you want to learn... (optional)',
            '钱包地址即账户 · 无需邮箱密码':'Wallet address = account, no email/password needed',
            '连接钱包即同意':'Connect wallet to agree to',
            '用户协议':'Terms',
            '和':'and',
            '隐私政策':'Privacy Policy',
            '推荐人钱包地址':'Referral Wallet Address',
            '推荐人信息':'Referrer Info',
            '推荐关系':'Referral Relationship',
            '修改':'Edit',
            '我的推荐链接':'My Referral Link',
            '分享给朋友，他们注册学习你就能赚取奖励':'Share with friends, earn when they learn',
            '今日':'Today','累计':'Total','本月':'This Month',
            '距升级还差':'To upgrade: need',
            '人':'people','业绩':'revenue',
            '升级为合伙人':'Upgrade to Partner',
            '合伙人享有区域运营权':'Partners get regional operation rights',
            '拿平台运营费80%分成':'80% of platform fees',
            '门槛：2万U':'Fee: 20,000U',
            '永久上限50人':'Max 50 partners permanently',
            '已上链':'On-chain','永久有效':'Permanently valid',
            '退课后课程作废':'Courses void after refund',
            '剩余代币全部一次性释放':'All remaining tokens released',
            '不退USDT':'No USDT refund',
            '不影响推荐人':'Does not affect referrer',
            '新增质押':'New Stake','持有':'Holding','解锁':'Unlock',
            '课程':'Course','方向':'Direction',
            '门课程':'courses','ACE总量':'ACE Total',
            '方案生成完毕':'Plan generated',
            '你的专属学习方案':'Your Personalized Plan',
            '方案已确认':'Plan confirmed',
            '付费后即可开始学习':'Pay to start learning',
            '重新规划':'Replan','确认方案':'Confirm Plan',
            '进入学习':'Enter',
            '管理后台只读取链上数据':'Admin panel only reads on-chain data',
            '当前连接':'Connected as',
            '管理员':'Admin',
            '数据已刷新':'Data refreshed',
        },
        ja: {
            '王牌学院':'ACE Academy','学技能 · 拿证书 · 赚代币':'スキル習得 · 証明書取得 · トークン獲得',
            '区块链+AI教育平台':'ブロックチェーン+AI教育プラットフォーム',
            '注册':'登録','登录':'ログイン','开始学习':'学習開始','浏览课程':'コース一覧','立即注册':'今すぐ登録',
            '下一步':'次へ','提交':'送信','取消':'キャンセル','复制':'コピー',
            '返回':'戻る','刷新':'更新',
            '第1步：输入推荐人地址':'ステップ1: 紹介者アドレス入力',
            '第1步：输入':'ステップ1: 入力','第2步：安全验证':'ステップ2: セキュリティ認証',
            '第3步：连接钱包授权':'ステップ3: ウォレット接続','第4步：注册完成':'ステップ4: 登録完了',
            '第1步：安全验证':'ステップ1: セキュリティ','第2步：连接钱包':'ステップ2: ウォレット接続',
            '第3步：签名授权':'ステップ3: 署名認証',
            '推荐人钱包地址':'紹介者ウォレットアドレス','推荐人':'紹介者',
            '必须通过':'必要: 紹介者経由の','邀请注册':'登録が必要',
            '如果有推荐链接，打开链接会自动填入':'紹介リンクがあれば自動入力されます',
            '输入推荐人地址 0x...':'紹介者アドレス入力 0x...',
            '向右滑动完成验证':'右にスライドして認証','验证通过':'認証完了','安全验证':'セキュリティ認証',
            '连接钱包并授权':'ウォレット接続','连接钱包':'ウォレット接続',
            '选择钱包':'ウォレット選択','小狐狸钱包':'MetaMask','扫码连接':'スキャン接続',
            '请在钱包中确认连接请求':'ウォレットで接続を確認してください',
            '需要输入密码或指纹确认':'パスワードまたは指紋確認が必要',
            '我已在钱包中确认':'ウォレットで確認しました',
            '授权签名':'署名認証','请在钱包中确认签名授权':'ウォレットで署名を確認してください',
            '此操作不消耗Gas费':'Gas代はかかりません','我已签名':'署名しました',
            '正在连接钱包':'ウォレット接続中','等待钱包确认':'ウォレット確認待ち',
            '正在验证签名':'署名検証中','签名验证成功':'署名検証成功',
            '授权成功':'認証成功','推荐关系已绑定，注册完成':'紹介関係バインド完了、登録完了',
            '注册成功':'登録成功','钱包地址':'ウォレットアドレス','用户ID':'ユーザーID',
            '已绑定':'バインド済み','进入学习中心':'学習センターへ',
            '签名授权登录':'署名してログイン','登录成功':'ログイン成功',
            '欢迎回到王牌学院':'ACE Academyへお帰りなさい','进入学习':'入場',
            '钱包已连接，请完成签名授权登录':'ウォレット接続済み、署名してログインしてください',
            '钱包地址即账户 · 无需邮箱密码':'ウォレットアドレス=アカウント · メール/パス不要',
            '连接钱包即同意':'ウォレット接続で同意','用户协议':'利用規約',
            '和':'と','隐私政策':'プライバシーポリシー',
            '准备好开始了吗？':'始める準備はできましたか？',
            '通过推荐链接注册，连接钱包，选课学习':'紹介リンクで登録、ウォレット接続、学習開始',
        },
        ko: {
            '王牌学院':'ACE Academy','学技能 · 拿证书 · 赚代币':'스킬습득 · 자격증취득 · 토큰획득',
            '区块链+AI教育平台':'블록체인+AI 교육 플랫폼',
            '注册':'가입','登录':'로그인','开始学习':'학습시작','浏览课程':'강의보기','立即注册':'지금 가입',
            '下一步':'다음','提交':'제출','取消':'취소','复制':'복사',
            '返回':'뒤로','刷新':'새로고침',
            '第1步：输入推荐人地址':'1단계: 추천인 주소 입력',
            '第1步：输入':'1단계: 입력','第2步：安全验证':'2단계: 보안 인증',
            '第3步：连接钱包授权':'3단계: 지갑 연결','第4步：注册完成':'4단계: 가입 완료',
            '第1步：安全验证':'1단계: 보안 인증','第2步：连接钱包':'2단계: 지갑 연결',
            '第3步：签名授权':'3단계: 서명 인증',
            '推荐人钱包地址':'추천인 지갑 주소','推荐人':'추천인',
            '必须通过':'필요: 추천인을 통한','邀请注册':'가입 필요',
            '如果有推荐链接，打开链接会自动填入':'추천 링크가 있으면 자동 입력됩니다',
            '输入推荐人地址 0x...':'추천인 주소 입력 0x...',
            '向右滑动完成验证':'오른쪽으로 슬라이드하여 인증',
            '验证通过':'인증 완료','安全验证':'보안 인증',
            '连接钱包并授权':'지갑 연결','连接钱包':'지갑 연결',
            '选择钱包':'지갑 선택','你选什么钱包':'지갑을 선택하세요',
            '小狐狸钱包':'MetaMask','扫码连接':'스캔 연결',
            '请在钱包中确认连接请求':'지갑에서 연결을 확인해 주세요',
            '需要输入密码或指纹确认':'비밀번호 또는 지문 확인이 필요합니다',
            '我已在钱包中确认':'지갑에서 확인했습니다',
            '授权签名':'서명 인증',
            '请在钱包中确认签名授权':'지갑에서 서명을 확인해 주세요',
            '此操作不消耗Gas费':'Gas 비용이 발생하지 않습니다',
            '我已签名':'서명했습니다','正在连接钱包':'지갑 연결 중',
            '等待钱包确认':'지갑 확인 대기 중',
            '正在验证签名':'서명 검증 중','签名验证成功':'서명 검증 성공',
            '授权成功':'인증 성공','推荐关系已绑定，注册完成':'추천 관계 연결 완료, 가입 완료',
            '身份验证通过':'신원 인증 완료','正在签名':'서명 중',
            '注册成功':'가입 성공',
            '钱包地址':'지갑 주소','用户ID':'사용자 ID',
            '已绑定':'연결됨','进入学习中心':'학습 센터로',
            '签名授权登录':'서명하여 로그인','登录成功':'로그인 성공',
            '欢迎回到王牌学院':'ACE Academy에 오신 것을 환영합니다',
            '进入学习':'입장','钱包已连接，请完成签名授权登录':'지갑이 연결되었습니다, 서명하여 로그인하세요',
            '钱包地址即账户 · 无需邮箱密码':'지갑 주소가 계정입니다 · 이메일/비밀번호 불필요',
            '连接钱包即同意':'지갑 연결 시 동의하는 것으로 간주',
            '用户协议':'이용약관','和':'및','隐私政策':'개인정보처리방침',
            '修改':'수정','推荐人信息':'추천인 정보','推荐关系':'추천 관계',
            '我的推荐链接':'내 추천 링크','分享给朋友，他们注册学习你就能赚取奖励':'친구와 공유하세요, 그들이 학습하면 보상을 받습니다',
            '今日':'오늘','累计':'누적','本月':'이번 달',
            '距升级还差':'승급까지: 필요','人':'명','业绩':'실적',
            '升级为合伙人':'파트너로 승격','合伙人享有区域运营权':'파트너는 지역 운영권을 가집니다',
            '拿平台运营费80%分成':'플랫폼 수수료 80% 분배',
            '门槛：2万U':'참가비: 20,000U','永久上限50人':'최대 50명 영구 제한',
            '已上链':'온체인','永久有效':'영구 유효',
            '退课后课程作废':'환불 후 강의 무효','剩余代币全部一次性释放':'남은 토큰 전체 일시 해제',
            '不退USDT':'USDT 환불 불가','不影响推荐人':'추천인에게 영향 없음',
            '新增质押':'신규 스테이크','持有':'보유','解锁':'해제',
            '课程':'강의','方向':'분야','门课程':'강의','ACE总量':'ACE 총량',
            '方案生成完毕':'계획 생성 완료','你的专属学习方案':'나만의 맞춤 학습 계획',
            '方案已确认':'계획 확인 완료','付费后即可开始学习':'결제 후 학습 시작',
            '重新规划':'다시 계획','确认方案':'계획 확인','进入学习':'입장',
            '管理后台':'관리 패널','全网统计':'전체 통계',
            '总用户数':'총 사용자','总学费收入':'총 수입',
            '资金钱包':'자금 지갑','平台运营USDT':'플랫폼 USDT',
            '护盘基金':'보호 기금','公益基金':'공익 기금',
            '做市管理':'시장 관리','推广统计':'홍보 통계',
            '推广者人数':'홍보자 수','合约地址':'컨트랙트 주소',
            '权限状态':'권한 상태','已丢弃':'폐기됨','未丢弃':'미폐기',
            '管理操作':'관리 작업','补充护盘基金':'보호 기금 충전',
            '提取超出部分':'초과분 인출','月度回购销毁':'월간 매수',
            '紧急暂停':'긴급 정지','返回首页':'홈으로',
            '学习进度':'학습 진행률','总学习时长':'총 학습 시간',
            '已学时长':'학습 시간','已释放代币':'해제 토큰',
            '课程列表':'강의 목록','完成本课':'완료','复习':'복습',
            '进行中':'진행중','参加考试':'시험 응시',
            '综合考试':'종합 시험','考试方向':'방향',
            '题目数量':'문제 수','题型':'유형','及格分数':'합격 점수',
            '考试时长':'시험 시간','考试次数':'응시 횟수','不限':'무제한',
            '开始考试':'시험 시작','考试通过！':'시험 합격!','未通过':'불합격',
            '答对':'정답','重新考试':'재응시','铸造链上证书':'자격증 발행',
            '课程库':'강의실','小时内容':'시간 콘텐츠',
            '课程成本':'강의 비용','入门':'입문','进阶':'중급','高级':'고급',
            '观看视频':'동영상 시청','实操练习':'실습','写代码':'코딩',
            '考试测评':'시험','零基础':'입문자','有基础':'기초 있음','比较熟悉':'숙련',
            'ACE当前价格':'ACE 가격','买入 ACE':'ACE 구매','卖出 ACE':'ACE 판매',
            '支付金额':'지불 금액','卖出数量':'판매 수량',
            '预计获得':'예상 획득','手续费':'수수료','销毁':'소각',
            '公益':'공익','实际到账':'실제 수령','底池':'풀',
            '已销毁':'소각됨','当前总量':'현재 총량','最近交易':'최근 거래',
            '我的资产':'내 자산','可用ACE':'사용 가능 ACE','锁定ACE':'잠금 ACE',
            '代币释放进度':'해제 진행률','已释放':'해제됨','未解锁':'미해제',
            '我的证书':'내 자격증','质押生息':'스테이킹','质押数量':'스테이크량',
            '质押期':'기간','年化收益':'연수익률','预期收益':'예상 보상',
            '到期时间':'만기','持有权益':'보유 혜택','退课':'환불','申请退课':'환불 신청',
            '身份':'역할','学员':'학생','大使':'앰버서더','合伙人':'파트너',
            '收入概览':'수입 개요','直推USDT':'직추천 USDT','团队代币':'팀 ACE',
            '代币释放':'해제','团队数据':'팀 데이터','直推人数':'직추천 수',
            '团队总人数':'팀 총원','团队业绩':'팀 실적','个人业绩':'개인 실적',
            '当前级别':'현재 등급','下一级':'다음 등급','直推明细':'직추천 상세',
            '账户信息':'계정 정보',
            '碎片时间学习':'자투리 시간','每天固定时间':'매일 고정 시간',
            '投入较多时间':'많은 시간 투자','找工作':'취업','创业':'창업',
            '提升技能':'스킬 향상','兴趣':'흥미',
            '准备好开始了吗？':'시작할 준비가 되셨나요?',
            '通过推荐链接注册，连接钱包，选课学习':'추천 링크로 가입, 지갑 연결, 학습 시작',
            '学技能':'스킬','拿证书':'자격','赚代币':'획득',
        },
        es: {
            '王牌学院':'ACE Academy','学技能 · 拿证书 · 赚代币':'Aprende · Certifícate · Gana Tokens',
            '区块链+AI教育平台':'Blockchain + IA Educación',
            '注册':'Registro','登录':'Acceso','开始学习':'Empezar','浏览课程':'Ver Cursos','立即注册':'Registrarse',
            '下一步':'Siguiente','提交':'Enviar','取消':'Cancelar','复制':'Copiar',
            '返回':'Volver','刷新':'Actualizar',
            '第1步：输入推荐人地址':'Paso 1: Dirección de Referencia',
            '第1步：输入':'Paso 1: Ingresar','第2步：安全验证':'Paso 2: Verificación de Seguridad',
            '第3步：连接钱包授权':'Paso 3: Conectar Wallet','第4步：注册完成':'Paso 4: Completado',
            '第1步：安全验证':'Paso 1: Seguridad','第2步：连接钱包':'Paso 2: Conectar Wallet',
            '第3步：签名授权':'Paso 3: Firmar',
            '推荐人钱包地址':'Dirección Wallet del Referente','推荐人':'Referente',
            '必须通过':'Requiere','邀请注册':'referencia para registrarse',
            '如果有推荐链接，打开链接会自动填入':'Si tienes enlace de referencia, se completa automáticamente',
            '输入推荐人地址 0x...':'Ingresa dirección de referente 0x...',
            '向右滑动完成验证':'Desliza a la derecha para verificar',
            '验证通过':'Verificado','安全验证':'Verificación de Seguridad',
            '连接钱包并授权':'Conectar Wallet','连接钱包':'Conectar Wallet',
            '选择钱包':'Seleccionar Wallet','小狐狸钱包':'MetaMask','扫码连接':'Escanear',
            '请在钱包中确认连接请求':'Confirma la conexión en tu wallet',
            '需要输入密码或指纹确认':'Contraseña o huella requerida',
            '我已在钱包中确认':'Confirmé en el wallet',
            '授权签名':'Firmar Autorización',
            '请在钱包中确认签名授权':'Firma en tu wallet para confirmar',
            '此操作不消耗Gas费':'Sin costo de gas','我已签名':'He firmado',
            '正在连接钱包':'Conectando wallet','等待钱包确认':'Esperando confirmación',
            '正在验证签名':'Verificando firma','签名验证成功':'Firma verificada',
            '授权成功':'Autorizado','推荐关系已绑定，注册完成':'Referencia vinculada, registro completo',
            '身份验证通过':'Identidad verificada','正在签名':'Firmando',
            '注册成功':'Registro Exitoso','钱包地址':'Dirección Wallet','用户ID':'ID de Usuario',
            '已绑定':'Vinculado','进入学习中心':'Entrar a la Plataforma',
            '签名授权登录':'Firmar para Acceder','登录成功':'Acceso Exitoso',
            '欢迎回到王牌学院':'Bienvenido de vuelta a ACE Academy','进入学习':'Entrar',
            '钱包已连接，请完成签名授权登录':'Wallet conectado, firma para acceder',
            '钱包地址即账户 · 无需邮箱密码':'La dirección Wallet es tu cuenta · Sin email ni contraseña',
            '连接钱包即同意':'Al conectar aceptas los','用户协议':'Términos',
            '和':'y','隐私政策':'Política de Privacidad',
            '修改':'Editar','推荐人信息':'Info del Referente','推荐关系':'Relación de Referencia',
            '我的推荐链接':'Mi Enlace de Referencia',
            '分享给朋友，他们注册学习你就能赚取奖励':'Comparte con amigos, gana cuando aprendan',
            '今日':'Hoy','累计':'Total','本月':'Este Mes',
            '距升级还差':'Para subir: necesitas','人':'personas','业绩':'ingresos',
            '升级为合伙人':'Ser Socio','合伙人享有区域运营权':'Socios tienen operación regional',
            '拿平台运营费80%分成':'80% de comisiones','门槛：2万U':'Costo: 20,000U',
            '永久上限50人':'Máximo 50 socios','已上链':'On-chain','永久有效':'Válido permanentemente',
            '退课后课程作废':'Cursos anulados tras reembolso',
            '剩余代币全部一次性释放':'Todos los tokens restantes liberados',
            '不退USDT':'No reembolso USDT','不影响推荐人':'No afecta al referente',
            '新增质押':'Nueva Inversión','持有':'Teniendo','解锁':'Desbloquear',
            '课程':'Curso','方向':'Dirección','门课程':'cursos','ACE总量':'ACE Total',
            '方案生成完毕':'Plan generado','你的专属学习方案':'Tu Plan Personalizado',
            '方案已确认':'Plan confirmado','付费后即可开始学习':'Paga para empezar',
            '重新规划':'Replanificar','确认方案':'Confirmar Plan',
            '管理后台':'Panel Admin','全网统计':'Estadísticas Globales',
            '总用户数':'Usuarios Totales','总学费收入':'Ingresos Totales',
            '资金钱包':'Billeteras','平台运营USDT':'USDT Plataforma',
            '护盘基金':'Fondo de Protección','公益基金':'Fondo Caritativo',
            '做市管理':'Gestión de Mercado','推广统计':'Estadísticas de Promoción',
            '推广者人数':'Promotores','合约地址':'Direcciones de Contrato',
            '权限状态':'Estado de Permisos','已丢弃':'Renunciado','未丢弃':'Activo',
            '管理操作':'Acciones','补充护盘基金':'Recargar Protección',
            '提取超出部分':'Retirar Exceso','月度回购销毁':'Recompra Mensual',
            '紧急暂停':'Pausa de Emergencia','返回首页':'Volver al Inicio',
            '学习进度':'Progreso','总学习时长':'Horas Totales',
            '已学时长':'Horas Aprendidas','已释放代币':'Tokens Liberados',
            '课程列表':'Lista de Cursos','完成本课':'Completar','复习':'Revisar',
            '进行中':'En Progreso','参加考试':'Examen',
            '综合考试':'Examen Completo','考试方向':'Dirección',
            '题目数量':'Preguntas','题型':'Tipo','及格分数':'Nota de Aprobación',
            '考试时长':'Duración','考试次数':'Intentos','不限':'Ilimitado',
            '开始考试':'Empezar Examen','考试通过！':'¡Aprobado!','未通过':'Reprobado',
            '答对':'Correctas','重新考试':'Reintentar','铸造链上证书':'Acuñar Certificado',
            '课程库':'Biblioteca de Cursos','小时内容':'horas contenido',
            '课程成本':'Costo','入门':'Principiante','进阶':'Intermedio','高级':'Avanzado',
            '观看视频':'Ver Video','实操练习':'Práctica','写代码':'Programar',
            '考试测评':'Examen','零基础':'Sin Base','有基础':'Con Base','比较熟悉':'Competente',
            'ACE当前价格':'Precio ACE','买入 ACE':'Comprar ACE','卖出 ACE':'Vender ACE',
            '支付金额':'Cantidad a Pagar','卖出数量':'Cantidad a Vender',
            '预计获得':'Esperado','手续费':'Comisión','销毁':'Quemar',
            '公益':'Caridad','实际到账':'Recibido','底池':'Pool',
            '已销毁':'Quemado','当前总量':'Suministro','最近交易':'Operaciones Recientes',
            '我的资产':'Mis Activos','可用ACE':'ACE Disponible','锁定ACE':'ACE Bloqueado',
            '代币释放进度':'Progreso de Liberación','已释放':'Liberado','未解锁':'Bloqueado',
            '我的证书':'Mis Certificados','质押生息':'Staking','质押数量':'Cantidad',
            '质押期':'Período','年化收益':'Rendimiento Anual','预期收益':'Recompensa Esperada',
            '到期时间':'Vencimiento','持有权益':'Beneficios','退课':'Reembolso','申请退课':'Solicitar Reembolso',
            '身份':'Rol','学员':'Estudiante','大使':'Embajador','合伙人':'Socio',
            '收入概览':'Resumen de Ingresos','直推USDT':'USDT Directo','团队代币':'ACE de Equipo',
            '代币释放':'Liberado','团队数据':'Datos de Equipo','直推人数':'Directos',
            '团队总人数':'Total Equipo','团队业绩':'Ingresos Equipo','个人业绩':'Ingresos Personales',
            '当前级别':'Nivel Actual','下一级':'Siguiente Nivel','直推明细':'Detalles Directos',
            '账户信息':'Información de Cuenta',
            '碎片时间学习':'Tiempo libre','每天固定时间':'Tiempo fijo diario',
            '投入较多时间':'Más tiempo','找工作':'Buscar trabajo','创业':'Emprender',
            '提升技能':'Mejorar habilidades','兴趣':'Interés',
            '准备好开始了吗？':'¿Listo para empezar?',
            '通过推荐链接注册，连接钱包，选课学习':'Regístrate, conecta wallet, aprende',
            '学技能':'Aprende','拿证书':'Certifícate','赚代币':'Gana',
        }
    };
    
    const dict = T[lang];
    if (!dict) return;
    
    // 遍历所有文本节点并翻译
    function walk(node) {
        if (node.nodeType === 3) { // 文本节点
            let text = node.textContent.trim();
            if (text && dict[text]) {
                node.textContent = dict[text];
            }
        } else if (node.nodeType === 1) { // 元素节点
            // 跳过script和style
            if (node.tagName === 'SCRIPT' || node.tagName === 'STYLE') return;
            for (let child of node.childNodes) {
                walk(child);
            }
        }
    }
    
    walk(document.body);
}

// 页面加载后执行
window.addEventListener('DOMContentLoaded', function() {
    setTimeout(translatePage, 100);
});

// 语言切换后也执行
window.addEventListener('load', function() {
    setTimeout(translatePage, 200);
});
